//! Weights from the last training run.
//!
//! Generated by `borscht train`, and checked in so the CLI, the WebAssembly
//! build and the published page all run the same commander with nothing to
//! fetch or load at runtime.
//!
//! `None` means no run has beaten the hand-written doctrine yet, and the
//! doctrine is what plays. That is the honest default: a commander should not
//! be replaced by a trained one that has not been shown to be better.
//!
//! Reset to `None` deliberately. The previous run's weights were fitted against
//! a different feature set -- there was no attacker flag -- and against a
//! different game, one in which a broken man left the field for good rather
//! than withdrawing to his muster point and coming back. They no longer
//! describe a commander for this battle, and keeping them because they were
//! expensive would be the worst reason to.

/// Trained commander weights, or `None` to use [`crate::brain::Net::doctrine`].
pub const TRAINED: Option<&[f32]> = None;
