//! Weights from the last training run.
//!
//! Generated by `borscht train`, and checked in so the CLI, the WebAssembly
//! build and the published page all run the same commander with nothing to
//! fetch or load at runtime.
//!
//! `None` means no run has beaten the hand-written doctrine yet, and the
//! doctrine is what plays. That is the honest default: a commander should not
//! be replaced by a trained one that has not been shown to be better.
//!
//! Reset to `None` for combined arms. The previous run's champion beat the
//! doctrine by +0.1999 on held-out seeds and was worth having, but it was
//! fitted to a game with one kind of soldier in it: no missiles in the air, no
//! charge worth timing, no spear wall to ride into, and a commander whose
//! eighteen inputs could not tell a division of cavalry from a battery of
//! catapults. Its 364 weights do not even fit the 444 the network now has.
//!
//! Keeping them because they were expensive would be the worst reason to.

/// Trained commander weights, or `None` to use [`crate::brain::Net::doctrine`].
pub const TRAINED: Option<&[f32]> = None;
